### ISSUE TITLE
Italic tokens

### ISSUE THREAD

**Issue by andrienko** [petepall/black_V2_theme#1]
The theme is almost exactly what I need... But it has this annoying italic for some tokens, making pipes look like slashes:

![Screenshot_20210204_173525](https://user-images.githubusercontent.com/6045971/106916059-6add7200-670f-11eb-9d42-ba20cf32a9d7.png)

**Comment by petepall** [comment]
@andrienko the requested chance is made. The extension is publishing at the moment check for version 1.06
